/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CS425.MPs;

import static org.junit.Assert.*;
import static org.junit.contrib.java.lang.system.ExpectedSystemExit.*;

import org.junit.Rule;
import org.junit.Test;
import org.junit.contrib.java.lang.system.ExpectedSystemExit;

public class QueryerTest {
    @Rule public final ExpectedSystemExit exit = ExpectedSystemExit.none();
    
    @Test
    public void testMainRequiresFourArguments() throws Exception {
        exit.expectSystemExitWithStatus(1);
        
        Queryer.main(new String[] {});
    }
}
